### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by nsarno** [aetrion/dns_erlang#4]
Any chance the readme could be updated with a bit of documentation? This library seems great but I'm not sure where to start with it :)

**Comment by aeden** [comment]
I'll see if I can put something in it at some point in the future. In the meantime, take a look at https://github.com/aetrion/erl-dns - it is a full-blown authoritative name server that uses this lib for all of the DNS packet construction and parsing.

**Comment by nsarno** [comment]
Thanks :+1:

**Comment by tfarina** [comment]
Hi, is this bug about updating the links of http://github.com/andrewtj/dns_erlang/? Or should I file one separately for this?

**Comment by aeden** [comment]
@tfarina This issue was more about documenting `dns_erlang` a bit to show how it can be used in your applications, so I'd open a separate ticket with details about where outdated links are.
